Repository justincanthony/gone_phishin, pull requests merged in 2021-09, with the labels that each got.

#7 Feature/file structure
  data/example-data.js
  src/App.css
  src/App.js
  src/App.test.js
  src/components/app/App.js
  src/components/audio_player/AudioPlayer.css
  src/components/audio_player/AudioPlayer.js
  src/components/container/Container.css
  src/components/container/Container.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.js
  src/components/show_card/ShowCard.css
  src/components/show_card/ShowCard.js
  src/components/track_card/TrackCard.css
  src/components/track_card/TrackCard.js
  src/contexts/ShowContext.js
  src/contexts/ThemeContext.js
Labels: architecture

#8 Feature/show provider
  README.md
  src/apiCalls.js
  src/components/app/App.js
  src/contexts/ShowContext.js
Labels: feature

#9 Feature/router
  package-lock.json
  package.json
  src/components/app/App.js
  src/index.js
Labels: feature

#11 Feature/show display feature
  package-lock.json
  package.json
  src/components/app/App.js
  src/components/container/Container.css
  src/components/container/Container.js
  src/components/show_card/ShowCard.css
  src/components/show_card/ShowCard.js
  src/index.js
Labels: feature, CSS, Javascript

#21 Feature/years dropdown
  src/components/app/App.js
  src/components/container/Container.js
  src/components/navbar/Navbar.js
  src/components/shows_container/ShowsContainer.css
  src/components/shows_container/ShowsContainer.js
  src/components/year_card/YearCard.js
  src/components/years_container/YearsContainer.js
  src/contexts/ShowContext.js
  src/years_dropdown/YearsDropdown.css
  src/years_dropdown/YearsDropdown.js
Labels: refactor, feature, Javascript

#26 Testing/shows display
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/integration/showDisplay_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  src/contexts/ShowContext.js
  src/years_dropdown/YearsDropdown.js
Labels: testing

#29 Refactor/drop down redirect
  src/components/years_dropdown/YearsDropdown.js
Labels: refactor, feature

#32 Feature/loading page
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/components/app/App.js
  src/components/container/Container.js
  src/components/shows_container/ShowsContainer.css
  src/components/shows_container/ShowsContainer.js
  src/contexts/ShowContext.js
  src/index.css
  src/phishLogoLoading.png
Labels: feature, CSS, Javascript

#34 Feature/track show footer stlying
  src/components/app/App.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/show_card/ShowCard.css
  src/components/show_card/ShowCard.js
  src/components/shows_container/ShowsContainer.css
  src/components/tracksContainer/TracksContainer.css
  src/components/tracksContainer/TracksContainer.js
  src/components/years_container/YearsContainer.css
Labels: CSS

#35 Feature/theme context
  public/index.html
  src/components/app/App.js
  src/components/navbar/Navbar.js
  src/components/shows_container/ShowsContainer.js
  src/components/theme_toggle/ThemeToggle.css
  src/components/theme_toggle/ThemeToggle.js
  src/components/track_card/TrackCard.js
  src/components/tracksContainer/TracksContainer.js
  src/components/year_card/YearCard.js
  src/components/years_container/YearsContainer.js
  src/contexts/ShowContext.js
  src/contexts/ThemeContext.js
  src/index.css
  src/index.js
Labels: CSS, Javascript

#36 Add link to logo
  src/components/navbar/Navbar.js
Labels: enhancement

#40 Feature/track display styling
  src/components/app/App.css
  src/components/app/App.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.js
  src/components/show_card/ShowCard.css
  src/components/show_card/ShowCard.js
  src/components/shows_container/ShowsContainer.js
  src/components/track_card/TrackCard.css
  src/components/track_card/TrackCard.js
  src/components/year_card/YearCard.css
  src/components/year_card/YearCard.js
  src/components/years_dropdown/YearsDropdown.js
  src/index.css
Labels: CSS

#41 Feature/errors
  src/components/app/App.js
  src/components/error_display/ErrorDisplay.css
  src/components/error_display/ErrorDisplay.js
  src/components/shows_container/ShowsContainer.js
  src/components/theme_toggle/ThemeToggle.js
  src/components/tracksContainer/TracksContainer.js
  src/components/years_container/YearsContainer.js
  src/contexts/ShowContext.js
Labels: error-handling

#44 Feature/error display plus styling
  src/components/error_display/ErrorDisplay.css
  src/components/error_display/ErrorDisplay.js
  src/error.png
  src/error_party.png
Labels: refactor, CSS

#45 Testing/error display
  cypress.json
  cypress/integration/errorDisplay_spec.js
  cypress/integration/showDisplay_spec.js
  cypress/integration/years_view.spec.js
  cypress/support/commands.js
Labels: testing

#46 Feature/cypress tracks display
  cypress/integration/showDisplay_spec.js
  cypress/integration/trackDisplay_spec.js
  cypress/support/commands.js
Labels: testing

#47 Feature/layout cleanup
  package-lock.json
  package.json
  src/components/error_display/ErrorDisplay.css
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/navbar/Navbar.js
  src/components/show_card/ShowCard.css
  src/components/show_card/ShowCard.js
  src/components/track_card/TrackCard.js
  src/components/tracksContainer/TracksContainer.css
  src/components/tracksContainer/TracksContainer.js
  src/components/year_card/YearCard.js
  src/components/years_dropdown/YearsDropdown.css
  src/contexts/ThemeContext.js
Labels: CSS, Javascript
